GLOSSARY = [
 ("Telecom and the network", [
  ("Microwave link", "An invisible radio beam between two towers that carries phone and internet traffic, like a torch beam aimed from one tower to the other. Rain weakens it."),
  ("Backhaul", "The connections that carry traffic from a tower back into the main network. Done by fibre cables or microwave links."),
  ("Fibre (optical fibre)", "A glass cable, usually underground, carrying data as light. Rain doesn’t affect it, so it gives no rain signal."),
  ("Tower / site", "A place with antennas and radio equipment. Tower companies may own the steel; the operator (Jio) runs the radios and owns the link data."),
  ("Frequency (GHz)", "How fast the radio wave vibrates; 1 GHz = a billion times a second. Higher-frequency links react more strongly to rain."),
  ("E-band", "Very high-frequency microwave (around 70–80 GHz) used for short, high-capacity links. Very rain-sensitive; can drop out in extreme rain."),
  ("Polarization", "The direction the radio wave wiggles: vertical (V) or horizontal (H). It slightly changes how rain affects the signal."),
  ("Path / path length", "The straight line between the two towers of a link, and its length in km."),
  ("TSL / RSL", "Transmitted signal level (power sent) and received signal level (power arriving), measured in dBm."),
  ("dB, dBm", "A log scale for power. dBm compares with one milliwatt. 3 dB less = half the power; 10 dB less = one-tenth."),
  ("Attenuation / signal loss", "How much weaker the signal is when it arrives. Rain adds extra attenuation."),
  ("Rain fade", "Telecom engineers’ name for a link weakening because of rain."),
  ("Fade margin / outage", "The spare signal a link can lose before it stops working. In extreme rain a link can drop out completely (an outage)."),
  ("Telemetry", "Measurements equipment sends about itself, such as signal levels, every minute or every 15 minutes."),
  ("NMS / NOC", "Network management system (software that stores telemetry) and network operations centre (the team watching the network)."),
  ("Network health data", "Jio’s own records of equipment faults, outages and maintenance. Used to stop a broken link being mistaken for rain."),
  ("Operator", "A mobile network company: Jio, Airtel, Vi, BSNL."),
 ]),
 ("Weather and measurement", [
  ("Hyperlocal", "Weather at the scale of a neighbourhood or street, not a whole city."),
  ("Rain rate (mm/h)", "How hard it’s raining: millimetres of water that would pile up in an hour."),
  ("Rain gauge", "A bucket-like instrument that measures rain at one spot. Very accurate there, but only there."),
  ("AWS", "Automatic weather station: a gauge plus sensors that reports by itself."),
  ("Doppler weather radar", "A radar that scans the sky and estimates rain over a wide area. IMD runs about 40 across India."),
  ("RADOLAN YW", "The German Weather Service’s radar rain product (5-minute, ~1 km squares) used as the answer key in our check."),
  ("Satellite rainfall", "Rain estimated from space. Covers everywhere but is coarse (roughly 10 km squares) and can lag."),
  ("IMD", "India Meteorological Department, the government weather agency."),
  ("BMC", "Brihanmumbai Municipal Corporation, Mumbai’s city government, which runs its own rain gauges."),
  ("Synoptic station", "An official weather station reporting at fixed times; the source of our India data."),
  ("NOAA GSOD", "The US weather agency’s public archive of daily station reports worldwide, including IMD’s."),
  ("Monsoon / north-east monsoon", "India’s main rainy season is June–September (south-west monsoon). The north-east monsoon brings rain to parts of south India from October to December."),
  ("Heatwave", "A spell of dangerously high temperature. IMD declares one in the plains when temperatures reach about 45°C."),
  ("Path-averaged rainfall", "The average rain along a link’s whole path. A link can’t tell where on the path the rain fell."),
  ("Wet antenna", "A film of water on the antenna that adds signal loss not caused by rain in the path; corrected (up to 1.5 dB)."),
  ("Baseline", "The signal loss a link would have if it were dry right now. Rain loss = loss − baseline."),
  ("Wet/dry detection", "Deciding which minutes are rainy by how much the signal wobbles compared with normal."),
  ("ITU-R P.838", "The international standard formula linking rain rate to signal loss per km: k = a × R^b."),
  ("Nowcast / forecast", "A nowcast describes rain now or in the next hour; a forecast predicts hours or days ahead. JioMausam observes; it doesn’t forecast."),
 ]),
 ("Our method and statistics", [
  ("Dataset", "A collection of measurements. Ours: 500 links × 2 channels × 15,840 minutes, plus radar."),
  ("pycomlink", "Free, open-source Python software from KIT, Germany, for turning microwave link data into rain."),
  ("Calibration / scale factor (K)", "One multiplier (1.17) that matches our totals to radar’s on the tuning days."),
  ("Tuning days / unseen test days", "10–12 May used to fit K; 13–20 May used only for scoring. Prevents marking our own homework."),
  ("Correlation (r)", "How closely two series rise and fall together: 1 = perfectly, 0 = not at all. Doesn’t check amounts."),
  ("Bias", "Our total ÷ the reference total. 0.82 means we read 18% low."),
  ("IDW (inverse distance weighting)", "Filling in a map: each square averages nearby links, nearer ones counting more (weight 1 ÷ distance²)."),
  ("Zone / square / grid", "The map is split into squares (about 3 × 4 km in our check). A grid is the full set of squares."),
  ("Trigger / event", "A rule that turns rain into a yes/no decision. Our event: 10 mm+ in any 3 hours in a zone on a day."),
  ("Events caught (hit rate)", "Of all real events (radar said yes), the share we also flagged: 68%."),
  ("Unconfirmed trigger", "We flagged an event radar didn’t see: 18% of our triggers. Not called “false” because radar can miss too."),
  ("Agreement", "Share of all decisions where both said the same: 94.6%, inflated by dry days."),
  ("Threshold", "The cut-off level, e.g. 10 mm. We also tested 5 and 15 mm."),
  ("Fusion", "Combining several sources (links, radar, gauges, satellite) into one better estimate."),
  ("Held-out gauges", "Gauges hidden from the system while it’s tuned, used only for scoring."),
  ("Back-test", "Running the system on past (archived) data to see how it would have done."),
  ("Accuracy gates", "Our pass marks: ≥80% of trigger events caught, totals within ±10%, under 15% unconfirmed."),
 ]),
 ("Business and strategy", [
  ("B2B / B2C / B2B2C", "Selling to businesses / to consumers / to businesses who pass it on to consumers."),
  ("Proving ground", "Where you test something on yourself first (Reliance) before selling it."),
  ("Decision infrastructure", "Not a map: alerts and triggers that plug into a business’s own decisions."),
  ("API", "A way for one company’s software to request data from another’s automatically."),
  ("Quick commerce", "10–30-minute grocery and goods delivery (e.g. Zepto, Blinkit, Instamart)."),
  ("Moat", "What makes a business hard to copy. Ours: integration, not the sensor."),
  ("Integration", "Connecting layers: Sense (network) → Understand (JioMausam) → Reach (Reliance) → Protect (insurers)."),
  ("KPI", "Key performance indicator: a number you track to judge success, e.g. site visits avoided."),
  ("Matched zones", "Comparing zones using JioMausam with similar zones not using it, on the same days."),
  ("Pilot / gates / stop-or-scale", "A small test with pass/fail points; pass all three to grow, otherwise stop."),
  ("JFS", "Jio Financial Services: a separately listed Reliance group company in financial services."),
 ]),
 ("Insurance", [
  ("Parametric insurance", "Pays a fixed amount when a measured trigger is crossed (e.g. rain above a level), without assessing each person’s loss."),
  ("Premium", "What the customer pays for cover."),
  ("Payout / benefit", "What the insurer pays when the trigger happens (prototype: ₹300)."),
  ("Loss ratio", "Payouts ÷ premiums. We assume 60%: ₹60 of every ₹100 goes back to customers."),
  ("Cap", "The most paid days in a year (5)."),
  ("Actuary / actuarial validation", "An insurance mathematician who sets prices and checks they’re safe."),
  ("Underwrite", "To take on the insurance risk and pay claims. Only a licensed insurer can."),
  ("Reinsurance", "Insurance for insurers, protecting them in very bad years."),
  ("Basis risk", "When the trigger and real life disagree: rained on but no payout, or the reverse."),
  ("Moral hazard / gaming", "People changing behaviour to collect a payout (e.g. logging in only when it rains)."),
  ("Adverse selection", "People buying cover only when they expect bad weather."),
  ("IRDAI", "Insurance Regulatory and Development Authority of India, the insurance regulator."),
  ("Regulatory sandbox", "A regulator’s scheme letting firms test new products in a limited, supervised way."),
  ("Shadow mode", "Running the system and recording would-be payouts without paying any money."),
  ("WBCIS", "India’s government weather-based crop insurance scheme: an existing parametric product."),
 ]),
]

# New question sets
VIDEO_Q = [
 ("Your video said every phone is a thermometer. Why isn’t that in your deck?",
  "It’s real research (Overeem et al., 2013), but it reads phone battery temperatures through an app, which needs users’ consent; it gives city-wide daily averages, not street-level readings; and phones heat up from use and charging. Not reliable enough to pay money on, so heat now comes from IMD stations and satellite.", None),
 ("Your video said the network measures 46.2°C in Nagpur. Can it?",
  "No. That screen was illustrative. Microwave links sense rain, not temperature. Heat data comes from IMD stations and satellite through the same engine.", None),
 ("Your video said ₹29 a month for heat and rain. Now prices are ₹45, ₹52, ₹208. Why?",
  "When we priced it with 25 years of IMD records, risk differed a lot by city. A flat ₹29 would lose money in Mumbai and Nagpur. ₹29 survives as our minimum price, which is what Ahmedabad gets.", None),
 ("Your video said ₹170 crore a year. Where did that go?",
  "It was 1% of Jio’s users × ₹29 × 12: the insurer’s premium pool on a guessed uptake, not Jio revenue. We removed it because we can’t back the uptake.", None),
 ("Your video said the payout lands in JioPay within two hours.",
  "A licensed insurer would pay through its own rail. ₹300 and the speed are prototype targets we’d measure in shadow mode.", None),
 ("Your video said JFS partners would underwrite it.",
  "We have no insurer partner. JFS is a separately listed group company and a natural partner, but any deal would be at arm’s length, and only after the accuracy and actuarial gates.", None),
 ("Your video said “Why only Reliance?”. Now you say integration. Isn’t that weaker?",
  "It’s more honest. Others could do parts of this; Reliance can connect all the layers and prove it on its own operations. “Only” was easy to attack.", None),
 ("Your video said “zero new hardware”. Now there are new gauges.",
  "Mostly existing infrastructure. A few gauges on Jio sites only where links are thin; that’s our safety net, not the plan.", None),
 ("Your video said the pilot was rain in Vidarbha and heat in Ahmedabad.",
  "A 90-day pilot starting now would miss Vidarbha’s monsoon (June–September) and Ahmedabad’s heat season (April–June). So we back-test archived Mumbai monsoon data, let the coverage audit choose the live city, and test heat in months 4–12.", None),
 ("Your video said New Energy could use it for solar output. Why drop that?",
  "Solar output depends on sunshine and cloud, which rain links don’t measure. We kept only uses our data can actually serve.", None),
 ("Your video said Jio would use it for rain-fade prediction.",
  "We now say detection, not prediction: can we tell rain-related signal loss from equipment faults before sending a crew? That’s something we can test.", None),
 ("Your video said heat could cost India 34 million jobs.",
  "The precise ILO estimate is working hours equal to about 34 million full-time jobs by 2030. Heat is no longer our lead, so it isn’t in the deck.", None),
 ("Your video said lakhs of stations in every district.",
  "We learned only microwave links count, and nobody outside Jio knows how many usable links there are. That’s Gate 1.", None),
 ("Your video was about farmers, riders, workers and vendors. Now it’s about businesses.",
  "Workers still benefit through Kavach later. Businesses that decide many times a day, starting with delivery, are a clearer first market.", None),
 ("Why should we trust you when your pitch changed this much?",
  "Because it changed for evidence. We tested our own idea, found where it broke, and kept what survived. That’s what the 90-day gates are for too.", None),
]
FIVE_W = [
 ("What is JioMausam?", "A weather-intelligence layer: signals Jio’s microwave links may carry, combined with radar and gauges, turned into zone-level alerts and triggers."),
 ("What is Mausam Kavach?", "An optional parametric insurance application: a fixed payout when a weather trigger is crossed, underwritten by a licensed insurer."),
 ("Who is it for first?", "Jio’s own network operations, then JioMart and MyJio; then delivery platforms, logistics, cities and insurers."),
 ("Who pays?", "Inside Reliance: savings. Outside: businesses pay for alerts and data. For Kavach, who pays is unproven and tested in the pilot."),
 ("Why Jio?", "It may already own the sensor (microwave links) and can connect sensing, intelligence, reach and protection."),
 ("Why now?", "Zone-level delivery decisions matter more than ever, extreme rain is rising, and operators keep adding microwave backhaul."),
 ("Why not insurance first?", "Who pays is unproven and links alone aren’t accurate enough to pay on. Insurance comes after the gates."),
 ("How does it work?", "Rain weakens the beam → we measure the extra loss → formula turns it into rain → combine with radar and gauges → zone alerts."),
 ("How accurate is it?", "Links alone caught 68% of rain events in our check; our bar for the combined system is 80%, with totals within ±10% and under 15% unconfirmed."),
 ("How do you make money?", "Intelligence fees (alerts, API, data), savings inside Reliance, and optional distribution fees if Kavach launches."),
 ("How much does the pilot cost?", "Mostly access and a small team on existing data; costed with Jio once Gate 1 shows what data exists."),
 ("How long until we know?", "Ninety days: coverage (days 1–30), accuracy (15–60), value (61–90)."),
 ("When would it launch?", "Reliance live and first clients in months 4–12 if the gates pass; cities and enterprises in Year 2; a national API in Year 3."),
 ("Where first?", "Wherever the coverage audit finds enough usable links; back-test on archived Mumbai monsoon data."),
 ("What could kill it?", "Too few usable links, no mix clearing the gates, or no measurable value inside Reliance. Each is a cheap stop."),
 ("What do you need from us?", "Link telemetry and network-health logs for one city, one Reliance operation for a shadow test, and 90 days."),
]
EXTRA_TECH = [
 ("How much does a raindrop actually weaken the signal?",
  "In our example, heavy rain (about 25 mm/h) added about 24 dB of loss over 8.5 km at 23 GHz: the received power dropped to well under 1% of normal. That big a change is easy to detect.", None),
 ("Why average the two channels?",
  "Each link has two directions; averaging them reduces random noise.", None),
 ("Why a 60-minute window for wet/dry?",
  "Long enough to see the signal wobble that rain causes, short enough to react within the hour. It’s the standard approach in the toolbox.", None),
 ("Why 1.12 × the 80th percentile?",
  "Each channel learns its own normal jitter; the 80th percentile is a “usually dry” level and 1.12 adds a small safety margin. It’s a tuning choice from the method, not a magic number.", None),
 ("What if a link’s power is changed automatically?",
  "Some radios raise their transmit power in rain. That’s why we use sent minus received, not received power alone.", None),
 ("Why 4 km zones and not 1 km?",
  "We merged radar’s 1 km grid 4 × 4 to match how far apart links typically are. Finer zones would mostly be guessed, not measured.", None),
 ("Why place each link at its midpoint?",
  "It’s the simplest choice for a path average. Better methods spread the value along the path; ours is a floor.", None),
]
