# Part 1 (like you're 10) and Part 3 (video vs deck)
KID = [
 ("1 · The problem", "Imagine one city where it is pouring in one neighbourhood and dry twenty kilometres away. That really happened in Mumbai on 26 July 2005: Santacruz got 944 mm of rain in a day, Colaba got 73. Now imagine you run a delivery company. Your phone says “Heavy rain in Mumbai”. Do you stop every rider in the city? Or keep everyone going? You don’t know <b>which streets</b> are flooded. That is the problem: there is weather information, but it is too blurry to make decisions street by street."),
 ("2 · The surprising idea", "Mobile towers talk to each other with invisible radio beams called <b>microwave links</b>, like a torch shining from one tower to another. When it rains, the raindrops soak up some of the beam, so less of it arrives at the other end. Think of shouting across a playground while it’s noisy: the louder the noise, the less of your voice gets across. If you measure how much weaker the beam got, you can estimate how hard it rained along that line. Jio has lots of towers, so Jio <b>may</b> already own a giant rain-measuring machine without knowing it."),
 ("3 · But only some towers can do it", "Not every tower uses these beams. Many are connected by <b>fibre</b> cables in the ground, and cables don’t feel rain. So the first question is simply: how many of Jio’s towers use beams, and where? Nobody outside Jio knows yet."),
 ("4 · Did we check if it works?", "Yes. Scientists proved the idea in 2006 (Israel) and made rain maps of a whole country in 2013 (the Netherlands). We wanted to check it ourselves, so we took a free research dataset from a university in Germany: 500 real tower beams, measured every minute for 11 days, plus weather radar as the “answer key”. We turned the beam signals into rain and compared. The beams followed the radar closely. But when we asked a strict question (“did it rain at least 10 mm in 3 hours in this neighbourhood today?”), the beams alone caught only <b>68 out of every 100</b> real heavy-rain events. Our target is 80. So beams alone are not good enough."),
 ("5 · So we team them up", "If one friend is sometimes wrong, you ask several friends. JioMausam combines the tower beams with weather radar (IMD), rain buckets called gauges (IMD and the Mumbai city corporation, BMC), satellites as a backup, and Jio’s own records of broken equipment (so a broken tower isn’t mistaken for rain). Then we test every combination and keep the cheapest one that reaches our target."),
 ("6 · Who uses it first?", "Jio itself. When a tower’s signal drops, Jio’s engineers have to decide: is it rain, or is something broken? If JioMausam can tell them before they send a repair team, Jio saves trips. Then JioMart can plan deliveries around rain, and the MyJio app can send rain alerts. If it helps inside Reliance, we sell the same alerts to other companies."),
 ("7 · What do other companies buy?", "Not a pretty map. They buy a message like “Rain is starting in Zone A”. Then <b>they</b> decide what to do: move riders, change delivery times, or pay riders more to keep working."),
 ("8 · What about insurance (Mausam Kavach)?", "Our first idea was insurance for workers: if heavy rain or extreme heat hits your area, you automatically get money, e.g. ₹300, without filling in forms. We still like it, but we found it is risky to start with: we don’t know who would pay, and beams alone are not accurate enough to pay people on. So insurance comes last, only if the system passes all accuracy checks, and a real insurance company (not Jio) carries the risk."),
 ("9 · How did we work out prices?", "We counted, from 25 years of weather records, how many days a year each city gets extreme rain or heat. Fewer bad days means a cheaper price. Mumbai’s extreme-rain cover works out to about ₹45 a month, Nagpur’s heat cover ₹52, Ahmedabad’s ₹29. These are starting points; a real insurer would set the final price."),
 ("10 · What are we asking for?", "Ninety days to answer three questions. Does Jio have enough beams? Does the team-up reach our accuracy target? Does it actually help a Reliance business? If all three say yes, grow it. If not, stop. That’s cheap, and nobody has to believe us; the test decides."),
]
KID_SUMMARY = "Jio’s towers may already be able to sense rain. We checked the science, found its limit, fixed it by combining sources, and want to prove it inside Reliance before selling it. Insurance is a possible extra, not the main business."

VIDEO_SCENES = [
 ("1 · Hook", "“India’s biggest weather network already exists.” Lakhs of stations · every district · switched on 24×7 · “It’s called Jio.”", "“Nobody noticed, because we call it Jio.”"),
 ("2 · Problem", "Weather is hyperlocal, our data isn’t · farmers, delivery riders, construction workers, street vendors · ~40 Doppler radars for 3.3 million km² (IMD) · 34M full-time jobs’ worth of work hours lost to heat by 2030 (ILO 2019) · months for a crop-insurance claim", "“…Heat alone could cost India thirty-four million jobs by 2030, and when insurance exists, claims take months.”"),
 ("3 · Insight", "Rain weakens the signal between towers (Messer et al., Science 2006) · phone batteries feel the city’s heat, 41.8°C city average (Overeem et al., GRL 2013) · “Every tower is a rain gauge. Every phone is a thermometer.”", "“We don’t build sensors. We become the sensor.”"),
 ("4 · Product", "JioMausam: a live, street-level weather map of India built from network data, zero new hardware, illustrative 1 km grid · MyJio recharge: ₹299 + Mausam Kavach heat + rain cover ₹29/mo · “46.2°C near you, measured by the network in Nagpur. Kavach triggered. ₹300 credited to JioPay, paid 2 hours after the trigger.”", "“When the network measures 45 degrees near you, the payout lands in your JioPay wallet within hours. No claim forms. No waiting.”"),
 ("5 · Business", "B2C Kavach ≈ ₹170 Cr/yr (1% of 500M users = 5M policies × ₹29/month), underwritten with JFS insurance partners · B2B cover + data: gig platforms, insurers, state disaster agencies, agri companies · customer zero: JioMart rainy-day demand, New Energy solar output, Jio rain-fade prediction", "“…about 170 crore rupees a year. Gig platforms and insurers buy the data. And Reliance is customer zero.”"),
 ("6 · Moat", "“Why only Reliance? Every layer. One roof.” Sense (lakhs of sites) · Reach (500M+ subscribers, every recharge) · Pay (JioPay, JioFinance) · Insure (JFS partners) · Use (JioMart, Reliance New Energy)", "“It owns every layer… under one roof.”"),
 ("7 · Roadmap and close", "Days 0–90 pilot: rain in Vidarbha, heat in Ahmedabad, validated against IMD gauges · months 4–9 IRDAI sandbox with JFS partners · Year 2 national map, open API", "“India will adapt to climate change by listening to the infrastructure it already has. This is JioMausam. Different by design.”"),
]

# (video claim, final deck, why we changed it, what to say if asked)
VIDEO_CHANGES = [
 ("“India’s biggest weather network already exists… lakhs of stations, every district.”",
  "“Jio may already own the infrastructure for a new weather-sensing layer.”",
  "Only microwave links sense rain; fibre does not. We don’t know how many of Jio’s sites use usable links, so “lakhs” and “biggest” were claims we couldn’t prove.",
  "“The video was our first version. We learned only microwave links work, so how many Jio has is now Gate 1.”"),
 ("“Every tower is a rain gauge.” / “…tells you exactly how hard it’s raining.”",
  "“Measure the excess loss and estimate path-averaged rainfall.” Links alone caught 68% of rain events.",
  "A link gives an average over its whole path, not an exact point reading, and our own test showed links alone miss about a third of heavy-rain events.",
  "“Our own check showed the limit, so we combine links with radar and gauges.”"),
 ("“Phone batteries… track air temperature. Every phone is a thermometer.” (41.8°C crowd-sourced)",
  "Removed. Heat comes from IMD weather stations and satellite, through the same engine. Towers sense rain only.",
  "The research is real (Overeem et al., 2013) but it reads phone battery temperatures through an app, which needs users’ consent under India’s data-protection law; it gives city-wide daily averages, not street-level readings; and phone heat is distorted by charging, pockets and air-conditioning. Not good enough to pay money on.",
  "“It’s published science, but it needs personal phone data and only works as a city-wide daily average, so for heat we use IMD stations and satellite.”"),
 ("“We don’t build sensors. We become the sensor.” / “Zero new hardware.”",
  "“The edge is integration, not the sensor.” New gauges on Jio sites only where links are thin.",
  "If links are thin somewhere, a few cheap gauges on Jio sites are the backup. Promising zero hardware would remove our safety net.",
  "“Mostly existing infrastructure; a few gauges only where links are thin.”"),
 ("“A live, street-level weather map of India… illustrative 1 km grid.”",
  "“Decision infrastructure, not a weather map”; “spatial weather grid”; near-real-time.",
  "Resolution depends on how dense the links are, and refresh speed depends on Jio’s data systems; both are pilot questions. Businesses pay for decisions, not maps.",
  "“We don’t promise 1 km everywhere; the pilot finds the real resolution.”"),
 ("“When the network measures 45 degrees near you…” / “46.2°C near you, measured by the network in Nagpur.”",
  "Heat trigger 47°C, from IMD stations and satellite.",
  "The network doesn’t measure temperature. And 45°C happens about 10 days a year in Nagpur, which would price cover at about ₹168 a month; 47°C (about 2 days a year) gives ₹52.",
  "“The phone mock-up was illustrative. Real heat data comes from IMD; 47°C keeps the price affordable.”"),
 ("“Mausam Kavach… insurance on your recharge for ₹29 a month” (heat + rain, everywhere).",
  "City-specific prices: Mumbai rain ₹45, Nagpur heat ₹52, Ahmedabad heat ₹29 (minimum), Mumbai Plus ₹208. Recharge is a Year-2 option.",
  "25 years of IMD records show risk differs a lot by city. A flat ₹29 would lose money in Mumbai and Nagpur. ₹29 survives as our minimum price.",
  "“When we priced it with real IMD data, one flat price didn’t fit; ₹29 became the minimum.”"),
 ("“The payout lands in your JioPay wallet within hours” / “₹300 credited, paid 2 hours after the trigger.”",
  "“A licensed insurer would underwrite and pay.” ₹300 is a prototype assumption.",
  "The insurer pays through its own rail (UPI or bank); nothing depends on JioPay. Speed is measured in shadow mode, not promised.",
  "“The insurer pays; we’d measure speed in shadow mode first.”"),
 ("“Underwritten with Jio Financial Services’ insurance partners.” / “Months 4–9: IRDAI sandbox, Kavach launched with JFS partners.”",
  "“A licensed insurer would underwrite.” Sandbox in months 4–12, only after the gates pass.",
  "We have no insurer partner, and JFS is a separately listed group company. Insurance launches only after accuracy and actuarial checks.",
  "“JFS is a natural partner, but any deal would be at arm’s length, and only after the gates.”"),
 ("“One percent of Jio’s users is five million policies, about ₹170 crore a year.”",
  "Removed from the deck. Q&A only, as an illustrative premium pool.",
  "Premiums belong to the insurer, not Jio; 1% uptake is a guess; and big untested numbers invite attack. (Maths: 5 million × ₹29 × 12 = ₹174 crore, rounded to ₹170.)",
  "“That was the insurer’s premium pool on a guessed uptake, not Jio revenue. We removed it.”"),
 ("Insurance-first business (“three layers of revenue”).",
  "Intelligence first. Value = intelligence fees (external) + savings inside Reliance (internal) + distribution fees (optional).",
  "Stress-testing showed who pays for insurance is unproven, and the weather intelligence underneath is the stronger business.",
  "“Our original idea was Kavach. Stress-testing showed the stronger business is the intelligence underneath it.”"),
 ("“Reliance is customer zero: JioMart rainy-day demand, New Energy solar output, Jio rain-fade prediction.”",
  "“Reliance is the first proving ground”: Jio network ops (hero), JioMart, MyJio.",
  "“Customer” implies Reliance has agreed to buy. Solar output needs sunshine and cloud data, which rain links don’t measure. “Prediction” became detection: telling rain from faults is testable.",
  "“We kept the uses our data can actually serve and turned them into tests.”"),
 ("“Why only Reliance? It owns every layer… under one roof.” (Sense, Reach, Pay, Insure, Use)",
  "“The edge is integration, not the sensor”: Sense → Understand → Reach → Protect.",
  "“Only” is easy to attack (Airtel has towers; weather firms have radar). Integration is defensible. “Pay” was dropped because the insurer pays.",
  "“Others could do parts of this; Reliance can connect all the layers.”"),
 ("“Weather is hyperlocal, our data isn’t” + ~40 radars for 3.3 million km².",
  "“India has a weather-decision problem” + the 944 vs 73 mm Mumbai example. Radar is an input we combine.",
  "Criticising radar invites “then just use radar”. A concrete Mumbai example proves the problem better than a national statistic.",
  "“Radar is part of our mix; the problem is turning observations into zone decisions.”"),
 ("“Heat alone could cost India 34 million jobs by 2030.”",
  "Removed.",
  "The ILO figure is the <i>equivalent</i> of 34 million full-time jobs in lost working hours, not 34 million jobs lost; the spoken line overstated it. And heat is no longer our lead.",
  "If asked: “The ILO estimated heat could cost India working hours equal to about 34 million full-time jobs by 2030.”"),
 ("Farmers, construction workers, street vendors, “months for a crop-insurance claim”.",
  "Businesses first (delivery, then logistics and cities, then agriculture and others); workers through optional Kavach.",
  "A focused first market beats helping everyone at once. Agriculture stays in tier 3.",
  "“We start where decisions happen many times a day: delivery.”"),
 ("“Days 0–90: rain in Vidarbha, heat in Ahmedabad, validated against IMD gauges.”",
  "Three gates (coverage, accuracy, value). The coverage audit picks the city; back-test on archived Mumbai monsoon data; heat in months 4–12.",
  "Timing: a pilot starting now would miss Vidarbha’s monsoon (June–September) and Ahmedabad’s heat season (April–June). And we can’t pick a city before knowing its coverage.",
  "“A 90-day window now has neither monsoon in Vidarbha nor heat in Ahmedabad, so we back-test archived data and let the audit pick the live city.”"),
 ("“Year 2: national map, open API.”",
  "Year 2: cities + enterprises; Year 3: national weather API. Only after all three gates pass.",
  "Scaling depends on coverage and calibration city by city.",
  "“City by city, only where coverage supports it.”"),
]
VIDEO_KEPT = ["Jio’s network as a weather signal, backed by Messer et al., Science 2006",
              "The names JioMausam and Mausam Kavach, and covering both rain and heat",
              "₹300 fixed benefit as the prototype payout, “no claim forms, no surveyor”",
              "Selling data and alerts to businesses (platforms, insurers, cities, agriculture)",
              "Using Reliance’s own businesses first",
              "A 90-day pilot, an IRDAI sandbox stage, and a national API later",
              "The closing idea: listen to infrastructure India already has · “Different by design”"]
VIDEO_NEW = ["The Mumbai 944 vs 73 mm example", "Our own test on 500 real links, with the honest 68% result",
             "Combining sources, with accuracy gates and held-out gauges", "Network-health data to tell rain from faults",
             "Network operations as the hero internal use", "The “customer decides” chain: Jio sells alerts, businesses decide",
             "City-specific prices from 25 years of IMD records", "Explicit stop-or-scale gates"]
