# Part C: question bank. Each item: (question, answer, optional "if pushed")
TOP = [
 ("What is JioMausam, in one line?",
  "A weather-intelligence layer built from signals Jio’s microwave network may already carry, combined with radar and gauges and turned into zone-level alerts that businesses act on. Insurance is one optional application on top."),
 ("Are you claiming Jio already has a working weather network?",
  "No. We know the physics works, and our own links-alone test shows it isn’t enough on its own. We don’t yet know Jio’s usable coverage, Indian performance or commercial value. So we’re asking for 90 days to measure those, with explicit gates and a stop-or-scale decision."),
 ("How did you get 68%?",
  "A public dataset from KIT in Germany: 500 real phone-network links, signal every minute for 11 days, with German weather radar as the answer key. Rain weakens the signal; a standard formula turns that loss into rain. For every ~4 km zone each test day we asked: 10 mm in 3 hours? Radar said yes 1,639 times; links also said yes on 1,120. 1,120 ÷ 1,639 = 68%. Below our 80% bar, which is why we never use links alone."),
 ("Why 80%?",
  "Our go/no-go bar for the pilot, set deliberately above the 68% links alone achieved, so passing proves the combined system adds value. It sits with two other gates so you can’t pass by triggering every day, and an insurer or use case can tighten it."),
 ("Why would Swiggy or Zomato pay?",
  "We don’t assume they will; that’s why we prove value inside Reliance first. The value case: rain shifts demand and rider supply zone by zone, so better zone decisions mean fewer late orders, less wasted incentive spend and fewer cancellations. Gate 3 measures it with matched zones before we sell outside."),
 ("Why can’t Google or a weather company do this?",
  "They forecast and they sell weather data, so they’re potential inputs or partners. What they don’t have is the signal inside Jio’s network, or Reliance operations to prove it on. Our edge is integration, not the sensor."),
 ("What stops Airtel from copying you?",
  "Nothing in the physics; the method is published. The edge is speed and integration: Jio’s network data plus Reliance’s operations, reach and financial ecosystem. If Airtel does it too, that validates the market, and businesses will buy whichever is more accurate in their zones."),
 ("What if Jio doesn’t have enough microwave links?",
  "Then Gate 1 tells us in the first month, cheaply. The system still runs on radar, gauges and network-health data for operations, and we can add gauges on Jio sites where links are thin. The question becomes how much Jio’s links add, not whether the business exists."),
 ("Why include insurance at all?",
  "It’s where we started and it matters to workers. But it launches only after the accuracy and actuarial gates pass, with a licensed insurer carrying the risk. If it never launches, the intelligence business still stands."),
 ("How did you price Kavach?",
  "From 25 years of IMD station records we counted how often each trigger happens, capped paid days at 5 a year, and applied: paid days × ₹300 ÷ 60% ÷ 12. ₹300 and 60% are prototype assumptions; an actuary sets final prices."),
 ("What do you need from Jio for the pilot?",
  "Mostly access, not money: link telemetry and network-health logs for one city, a small data team with a meteorology partner, IMD/BMC data, and one Reliance operation willing to run a shadow test. We’d cost it properly with Jio once Gate 1 shows what data exists."),
 ("What is your single biggest risk?",
  "Coverage: whether Jio has enough usable microwave links where it matters. That’s exactly why it is Gate 1, and it costs almost nothing to check."),
]

SECTIONS = []
def S(title, intro, items): SECTIONS.append((title, intro, items))

S("Competition and alternatives", "Judges will test whether someone bigger already does this. Never attack competitors; position them as inputs, partners or proof the market is real.", [
 ("Google and DeepMind already do AI weather forecasting. Why you?",
  "Forecasting and observing are different jobs. AI forecasting models predict weather hours to days ahead from global data. JioMausam observes rain happening now, zone by zone, and turns it into operational alerts. They complement each other: a forecast says rain is likely this afternoon; JioMausam says it is raining in Zone A now. A forecast model could even use our observations as an input.", None),
 ("Weather companies already sell hyperlocal weather APIs (e.g. The Weather Company, Tomorrow.io, Skymet).",
  "Yes, and platforms already buy from them. Their hyperlocal products are mostly models built on radar, satellite and stations. None of them has Jio’s network signal. If our links add accuracy, that’s a real edge; if they don’t, our pilot’s “radar + gauges, no links” baseline shows it and we won’t pretend otherwise. Some of these firms could be partners or data buyers.", None),
 ("Hasn’t this been tried commercially already?",
  "The idea isn’t new, which is what makes it credible. Researchers proved it in Israel (2006) and mapped a whole country in the Netherlands (2013), and weather startups and telecom vendors have built or piloted products on wireless-signal data. What’s new is doing it in India, on Jio’s network, combined with IMD data and proven inside Reliance operations.",
  "Researchers and companies have worked on this for over a decade. We’d rather show our own check than quote other people’s claims."),
 ("IMD has radars and is expanding under Mission Mausam. Doesn’t that make you redundant?",
  "No. IMD is an input and a natural partner. Its radars and gauges are in our mix. IMD’s job is public forecasts and warnings; ours is turning observations into decisions for specific operations. More IMD radars make JioMausam better, not obsolete.", None),
 ("Mumbai already has BMC rain gauges and hyperlocal weather apps.",
  "Exactly, and they’re inputs we combine, not rivals. The real question is whether Jio’s links add information between gauges. The pilot measures that directly with the “radar + gauges, no links” run.", None),
 ("What stops Airtel, Vi or BSNL?",
  "Nothing technical; the method is open. The edge is integration and speed: Jio’s network signal plus Reliance’s operations to prove value on, its enterprise reach and its financial ecosystem. A competitor doing it would confirm the market.",
  "“Could you work with other operators?” Possibly later: more links mean better coverage. We’d start with Jio’s own network."),
 ("Why not tower companies? They own the towers.",
  "They own the steel and the sites. The radio links and their signal data belong to the operator running them. That’s Jio.", None),
 ("Delivery platforms can build this in-house.",
  "They can and should build their own decision logic. What they can’t build is the raw network signal. Our product is the intelligence feed they plug into their own dispatch systems.", None),
 ("Why not just buy weather data and skip Jio’s links?",
  "That is our pilot baseline. If links add nothing, we say so; then the case rests on the decision layer and Reliance’s distribution, and the moat is weaker. Better to learn that in 90 days than after a big launch.", None),
 ("Insurers already sell parametric weather insurance (e.g. crop insurance).",
  "Yes: India already runs a weather-index crop insurance scheme (WBCIS), so parametric cover is familiar to insurers and the regulator. That’s why Kavach plugs into licensed insurers instead of competing with them. We supply trigger data.", None),
 ("Satellites cover all of India. Why not use them?",
  "Satellite rainfall is open and covers everything, but it’s coarse and can lag, so it’s our fallback, not the main source. The pilot evaluates satellite sources on coverage, latency, resolution and licensing.",
  "Open satellite rainfall products are roughly 10 km squares, far coarser than zone decisions need."),
 ("Why not put IoT rain sensors everywhere?",
  "Hardware at scale means capex, maintenance and theft. We add gauges only where links are thin, on Jio sites that already have power, security and connectivity.", None),
 ("Why not crowdsource from smartphones?",
  "Phones don’t measure rain; user reports are noisy and sparse in heavy rain. It could become a confirmation signal later, but it isn’t the core.", None),
 ("Why not use 5G or phone-to-tower signals?",
  "Backhaul links are fixed point-to-point paths with known length and frequency, so the physics is clean. Phone-to-tower signals vary with movement, buildings and indoor use, so rain is much harder to separate out.", None),
])

S("The problem and the idea", "Show the problem is real without overclaiming.", [
 ("Is this a real problem? Platforms already handle rain.",
  "They handle it with city-level information and manual calls. Platforms charging a rain fee shows rain clearly matters to their economics. Our claim is narrow: zone-level precision could improve those decisions, and Gate 3 measures whether it does.", None),
 ("One day in 2005 isn’t evidence.",
  "Agreed, so we checked recent years too. In the 2020–2024 monsoons, Santacruz and Colaba both reported on 89 days. On 15 of them at least one station had heavy rain (64.5 mm+), and on 5 of those 15 the other station got less than half. Rain differing sharply across one city is routine, not a one-off.", None),
 ("Isn’t this a solution looking for a problem?",
  "We started from a problem, riders losing income and businesses deciding blind in rain, and stress-tested our way to the solution. And we test value before scaling, so if the problem isn’t worth solving, Gate 3 says so.", None),
 ("Why rain and not floods or air quality?",
  "Rain is what microwave physics measures. Flood alerts for sites are a downstream use of rain data. Air quality can’t be measured this way.", None),
 ("Why Mumbai?",
  "Most heavy-rain days of our three cities (about 12 a year), dense operations, and the clearest example of rain varying within a city. But the live-test city is chosen by the coverage audit, not by us.", None),
 ("“Decision infrastructure” sounds like jargon.",
  "It means we don’t sell a weather map. We sell alerts and triggers that plug into a business’s own decisions: dispatch, pausing routes, incentives, payouts.", None),
])

S("The technology", "Plain answers; admit what the pilot must measure.", [
 ("How exactly does rain weaken the signal?",
  "Raindrops absorb and scatter microwave energy. The heavier the rain, the bigger the loss. The relationship is an international standard (ITU-R P.838) and depends on the link’s frequency, polarization and length.", None),
 ("Which frequencies work?",
  "Links in our test ran from about 6 to 39 GHz; higher frequencies react more strongly to rain. Very short, very high-frequency links are highly sensitive but can drop out in extreme rain. The coverage audit lists which of Jio’s bands are usable.", None),
 ("Jio is mostly fibre. Doesn’t that kill the idea?",
  "In dense cities fibre may dominate; fibre gives no rain signal. That’s why coverage is Gate 1. Where links are thin we lean on radar, gauges and new gauges on Jio sites. The business doesn’t depend on Jio’s links alone; the pilot measures what they add.", None),
 ("In very heavy rain, doesn’t the link just drop?",
  "Some links can, at extreme rain. A drop-out itself tells you rain passed a high level, and radar and gauges cover the gap. We treat outages as information, not missing data.", None),
 ("How do you tell rain from an equipment fault?",
  "Three ways: the pattern (rain builds and fades; faults are sudden), neighbours (rain hits nearby links together; a fault hits one), and Jio’s network-health flags for faults, outages and maintenance. That’s why network health is a source on slide 4.", None),
 ("What is the wet-antenna problem?",
  "Water on the antenna adds loss that isn’t rain along the path. We correct it with a standard method (Schleiss et al., 2013), allowing up to 1.5 dB.", None),
 ("What about fog, humidity and temperature?",
  "Their effect is much smaller than rain at these frequencies and changes slowly, so the dry-weather baseline absorbs it.", None),
 ("Does Jio even store this data? How often?",
  "Operators’ network management systems record signal levels; often as 15-minute minimum and maximum values. The Netherlands country-wide maps were built from exactly that kind of operator data. How often and how far back Jio’s data goes is part of Gate 1. Live minute-level data would need polling.", None),
 ("A link averages rain along its path. How do you know where it rained?",
  "Right: one link gives an average. Many crossing links plus radar and gauges locate the rain; that’s the fusion step that builds the grid.", None),
 ("What resolution will you get?",
  "It depends on link density and layout. Our German check used ~4 km zones. We don’t promise 1 km everywhere; the pilot finds the real resolution city by city.", None),
 ("How fast are alerts?",
  "Near-real-time; how near depends on how fast telemetry can be pulled. Operational decisions need minutes, not seconds. The pilot measures it.", None),
 ("Can JioMausam forecast?",
  "It observes current rain. Short-term forecasts could be built on top later by tracking movement, but we don’t claim that.", None),
 ("Is the ITU formula valid for Indian monsoon rain?",
  "The formula assumes typical raindrop sizes; monsoon rain can differ. That’s exactly why local calibration against Indian gauges is part of Gate 2.", None),
 ("How much data and computing does this need?",
  "Modest: a few numbers per link per minute. Jio already processes far larger telemetry every day.", None),
 ("Will Jio’s security team allow this?",
  "Data stays inside Jio. JioMausam only outputs aggregated rain per zone, never network layout or customer data. Network performance readings aren’t personal data.", None),
])

S("Our 68% check", "Know this cold. Answer, then return to strategy.", [
 ("Why German data and not Indian or Jio data?",
  "Jio’s data isn’t public. This is the standard public research dataset with real links and a radar answer key. Jio’s real number is exactly what the pilot measures.", None),
 ("Only 11 days?",
  "Yes: it’s a check of the method, not a final validation. It still gives 14,256 yes/no decisions on 8 unseen days. The pilot uses a full monsoon.", None),
 ("May in Germany isn’t a monsoon.",
  "Agreed. Monsoon rain is heavier and longer; heavier rain gives a stronger signal but more drop-out risk. That’s why Gate 2 back-tests archived Mumbai monsoon data.", None),
 ("Radar isn’t ground truth.",
  "Agreed; it was the reference in that dataset. That’s why we say “not confirmed by radar”, not “false”. The pilot checks against held-out rain gauges.", None),
 ("Did you tune it to look good?",
  "We tuned one scale factor on the first 3 days only, then tested on the 8 days it had never seen.", None),
 ("One scale factor for 500 links sounds crude.",
  "It is, deliberately. Production systems calibrate locally. Our result is a floor, not a ceiling.", None),
 ("How closely did links track radar?",
  "Network-wide hourly match 0.95; a typical single link 0.88; map level 0.78. The trigger test is harsher: a 9 mm estimate against an 11 mm event counts as a miss.", None),
 ("Why do links read 18% low?",
  "The tuning days had very little rain, so the scale factor was fitted on light rain, and path-averaging smooths peaks. Local calibration in the pilot addresses it.", None),
 ("Why 10 mm in 3 hours?",
  "Our heavy-shower rule for the check. We also tried 5 mm and 15 mm: 64% and 54% caught. None got near 80%, so the conclusion doesn’t depend on the rule.", None),
 ("Which software?",
  "Python with pycomlink, the open-source toolbox from KIT that implements the published method, plus our own code for the zone map and the comparison.", None),
 ("Can we check your work?",
  "Yes. The data is public, the code is in our repository, the workbook recomputes 68% from the 14,256 decisions, and our Test Lab reruns everything in a browser.", None),
 ("Did you build a model?",
  "No new model and no machine learning. We ran the published method on public data and calculated the result ourselves.", None),
 ("Is 68% good or bad?",
  "For one source with simple processing it’s a reasonable floor. For paying claims it isn’t enough. That gap is why the product combines sources.", None),
 ("What is the 18% unconfirmed?",
  "Of our 1,364 triggers, 244 weren’t seen by radar. Some are our errors, some may be radar misses.", None),
])

S("Accuracy gates and combining sources", "", [
 ("Why ±10% on rain totals?",
  "If amounts are off, prices and payouts are off. Our links-alone check read 18% low, so this gate forces calibration.", None),
 ("Why under 15% unconfirmed?",
  "So a system can’t “pass” the 80% gate by triggering every day. Our check had 18%.", None),
 ("Who sets the gates?",
  "We set them as the pilot’s go/no-go. Jio, and for Kavach an insurer, can tighten them.", None),
 ("What are held-out gauges?",
  "Gauges kept hidden from the system while it’s tuned, and used only to score it, so we’re not marking our own homework.", None),
 ("What if no combination clears 80%?",
  "Then we don’t scale externally and Kavach stays in shadow or is dropped. We’d keep only uses that need less precision, like network operations, if Gate 3 shows value.", None),
 ("How do you know what each source costs?",
  "We don’t claim prices. The slide shows who provides each source. The pilot puts a rupee figure on each, and the rule picks the cheapest mix that clears the bar.", None),
 ("What is “network health” data?",
  "Jio’s own alarms and logs: equipment faults, outages, maintenance windows. It removes signal drops that aren’t rain.", None),
 ("What would new gauges on Jio sites cost?",
  "Priced in the pilot. They’re only for areas where links are thin, and Jio sites already have power, security and connectivity.", None),
 ("When would you buy commercial data?",
  "Only if it lifts accuracy enough to justify its cost. Otherwise not.", None),
])

S("Reliance as the proving ground", "", [
 ("Why start inside Reliance?",
  "Jio owns the data and the decisions, savings are measurable, and there’s no sales cycle. It proves value before anyone outside has to pay.", None),
 ("Doesn’t Jio’s network team already know rain fade?",
  "It may. Then Gate 1 confirms cheaply what weather information is available. If it doesn’t, that’s new value. Either way the same telemetry feeds the weather layer.", None),
 ("How would network operations save money?",
  "By not sending crews for rain-related signal loss that recovers on its own, prioritising real faults, and warning sites at flood risk. Gate 3 measures site visits avoided, fault-resolution time and weather outages correctly identified.", None),
 ("What does JioMart get?",
  "Rain-aware delivery promises, dispatch and zone pauses. Measured by late deliveries, cancellations and rider availability.", None),
 ("You said it isn’t a consumer app, but MyJio sends alerts.",
  "MyJio tests reach inside an existing app. We’re not building a standalone consumer weather app business.", None),
 ("Will Reliance businesses actually cooperate?",
  "That’s part of the ask: one operation for one shadow test. The coverage audit decides which city.", None),
])

S("Market, customers and selling", "", [
 ("What exactly do you sell?",
  "Zone alerts (rain starting, intensity), live API feeds, historical rain records for audits and claims, and trigger data for insurers.", None),
 ("How will you price the intelligence product?",
  "After the pilot, benchmarked to the value Gate 3 measures. Likely a subscription per city or zone, or by API volume. We won’t guess numbers before we have evidence.", None),
 ("What is the market size?",
  "We deliberately don’t headline one; we’d build it bottom-up after the pilot. For Kavach alone, 50,000 Mumbai riders on Plus is about a ₹12.5 crore premium pool a year, which is the insurer’s money, not Jio revenue.",
  "If asked about the video’s ₹174 crore: 50 crore users × 1% × ₹29 × 12. It is an illustrative premium pool, B2C uptake is unproven, so we removed it."),
 ("Why delivery first?",
  "It makes the most rain-sensitive real-time decisions, zone by zone, many times a day.", None),
 ("Why would BMC or a city buy?",
  "Flood response, pump deployment, traffic management. Public-sector sales are slower, so cities are tier 2.", None),
 ("What about agriculture?",
  "Rainfall records for crop insurance and advisories; rural areas may rely more on microwave backhaul. Tier 3, and unproven.", None),
 ("How do you reach customers?",
  "Potentially through Jio’s enterprise sales relationships and Reliance’s partners. That’s the “Reach” layer.", None),
 ("Why buy from Jio rather than a weather firm?",
  "Only if Jio’s links add accuracy in the buyer’s zones, plus an auditable multi-source trigger and integration with Reliance’s ecosystem. If links don’t add accuracy, we don’t claim an edge.", None),
])

S("Why Jio, the moat and the economics", "", [
 ("The method is open-source. Where is the moat?",
  "Access to Jio’s private link data, calibration history built over seasons, integration with Reliance operations, and distribution. The method is open; the signal isn’t.", None),
 ("Why should Reliance invest?",
  "Low capex because the infrastructure exists, internal savings first, optional upside, and a strategic data asset. And it costs 90 days to find out.", None),
 ("Where are your revenue projections?",
  "None on the slide on purpose. We’d rather show value measured in Gate 3 than invented forecasts.", None),
 ("Savings inside Reliance aren’t revenue.",
  "Correct, which is why slide 7 separates external revenue from internal value.", None),
 ("JFS isn’t part of Reliance any more.",
  "It’s a separately listed group company and a natural partner. Any arrangement would be at arm’s length, with a licensed insurer carrying the risk.", None),
 ("What does Jio actually risk?",
  "A small pilot. No insurance risk; shadow mode protects reputation.", None),
 ("How big are distribution fees?",
  "Illustratively, 15–25% of a ₹12.5 crore premium pool is ₹1.9–3.1 crore. Small, which is exactly why insurance is not the business.", None),
])

S("Kavach (insurance)", "Keep Kavach clearly optional and clearly the insurer’s risk.", [
 ("What is parametric insurance?",
  "It pays a fixed amount when a measured trigger is crossed, like rain above a level in your zone, without assessing individual losses.", None),
 ("Why can’t Jio be the insurer?",
  "Insurance needs an IRDAI licence and capital. Jio supplies data; a licensed insurer underwrites and pays.", None),
 ("What is basis risk?",
  "A worker gets rained on but no payout triggers, or the reverse. Small zones, multi-source triggers and a review process reduce it, which is why the accuracy gates come first.", None),
 ("Won’t people log in just to collect payouts?",
  "Eligibility requires being already active in the zone before the event began, checked against platform activity logs.", None),
 ("Won’t people buy only when heavy rain is forecast?",
  "That’s adverse selection. The answer is season-long or annual cover, or platform group cover, with no buying in mid-event.", None),
 ("Who pays: platforms or riders?",
  "Unproven: platform-sponsored, co-funded or individual. The pilot tests it.", None),
 ("Why would a platform pay ₹2,500 a year for at most ₹1,500 of payouts?",
  "The gap is the insurer’s costs at an assumed 60% loss ratio. A platform could fund the allowance itself using our trigger data, and Jio earns from the data either way.", None),
 ("How is the money paid? JioPay?",
  "Through the insurer’s payment rail (UPI or bank). We don’t depend on any particular wallet. Shadow mode measures the speed.", None),
 ("What is the IRDAI sandbox and shadow mode?",
  "Shadow mode computes would-be payouts without moving money. The regulator’s sandbox lets insurers test new products within limits. Real payouts come only after the gates.", None),
 ("Why ₹300?",
  "A round prototype figure, roughly part of a day’s earnings. The insurer or platform would set the real benefit.", None),
])

S("Pricing", "Every price is illustrative. Know the formula and one worked example.", [
 ("Walk me through ₹45.",
  "Mumbai sees ≥204.5 mm in a day about 1.08 times a year. 1.08 × ₹300 = ₹324 of expected payouts; ÷ 0.6 = ₹540 a year; ÷ 12 = ₹45 a month.", None),
 ("And ₹52, ₹29, ₹208?",
  "Nagpur: 2.2 days a year at 47°C+, but capped at 5 paid days a year that averages 1.24 paid days → ₹52. Ahmedabad: 0.64 paid days → ₹27, raised to our ₹29 minimum price. Mumbai Plus: ≥64.5 mm happens about 12 days a year, every year at least 5, so it always pays 5: 5 × 300 ÷ 0.6 ÷ 12 = ₹208.", None),
 ("Why a 60% loss ratio?",
  "An illustrative assumption: ₹60 of every ₹100 goes back as payouts, ₹40 covers costs and margin. An actuary sets the real figure.", None),
 ("Why cap at 5 days a year?",
  "It limits the worst-year cost and keeps the price predictable. With a 3-day cap, Plus would be ₹125.", None),
 ("Why ₹29 for Ahmedabad when the maths says ₹27?",
  "Our chosen minimum price, so even very low-risk cover pays for basic administration.", None),
 ("Why 47°C and not 45°C?",
  "45°C happens about 10 days a year in Nagpur, which would price Basic at about ₹168 a month. 47°C targets rare extremes at an affordable ₹52.", None),
 ("Why ≥204.5 mm for Mumbai Basic?",
  "That’s IMD’s “extremely heavy rain” level: rare (about once a year), so Basic stays cheap. IMD’s “heavy rain” level (64.5 mm) is the broader Plus product. A very-heavy trigger (115.6 mm) would price at ₹165.", None),
 ("Your live trigger is 10 mm in 3 hours. Why price on 64.5 mm a day?",
  "₹208 isn’t priced from that prototype rule. It uses 25 years of daily IMD heavy-rain history, capped at five paid days. The pilot measures the 3-hour trigger’s real frequency and recalibrates before any launch.", None),
 ("What happens in bad years?",
  "We replayed every year from 2000 to 2024. Worst years: Mumbai Basic 2019 paid 222% of premiums, Nagpur 2013 242%, Ahmedabad 2018 469%. Plus was 60% every year because it always hits its cap. Bad years are why a licensed insurer pools risk across cities and years, with reinsurance.", None),
 ("Is NOAA’s data reliable?",
  "It’s NOAA’s public archive of IMD’s own station reports. We kept only years with at least 330 days of reports, including 110 in June–September; all 25 years passed. Missing days count as no trigger, so if anything we slightly undercount.", None),
 ("Why these three cities?",
  "Mumbai is India’s rain extreme; Nagpur and Ahmedabad are heat extremes. Together they show one flat price can’t fit India.", None),
 ("Climate change makes 25-year averages wrong.",
  "Trends matter; studies report a sharp rise in widespread extreme rain over central India since 1950. An actuary would weight recent years and add a loading. Our numbers are a starting point.", None),
 ("Would a rider pay ₹45 a month for about one payout a year?",
  "Maybe not, which is why Basic is optional and who pays is tested. Basic is cheap cover for rare extremes, not an income product.", None),
])

S("Pilot and roadmap", "", [
 ("Is 90 days realistic?",
  "Yes, because nothing new is built first. The audit is desk work on existing telemetry, the back-test uses archived data, and the live test is about a month. The phases overlap.", None),
 ("Which city, and when?",
  "The coverage audit chooses. A live test now would run in a north-east-monsoon city (rain from October to December); Mumbai’s 2027 monsoon falls in months 4–12.", None),
 ("What if it doesn’t rain in days 61–90?",
  "The back-test replays archived monsoon events, including network-operations value. The full live test runs in Mumbai’s 2027 monsoon.", None),
 ("What are matched zones?",
  "Zones using JioMausam compared with similar zones that aren’t, on the same days. The difference is the value.", None),
 ("What are your stop criteria?",
  "Any gate fails: stop, or narrow to what passed. No external scaling until all three pass.", None),
 ("Year 2 says “Basic at recharge”. Didn’t you say B2C is hard?",
  "It’s optional and only happens if Kavach passes its gates and an insurer partners. Recharge is just a distribution channel.", None),
 ("How do you get to a national API by Year 3?",
  "City by city: audit coverage, calibrate locally, launch where coverage supports it.", None),
])

S("Feasibility and scalability", "", [
 ("Is it technically feasible?",
  "The physics is proven, the tools are open, the data exists in operator systems, and we ran the method ourselves on real link data.", None),
 ("Operationally?",
  "A small team on existing telemetry; no new hardware except optional gauges where links are thin.", None),
 ("Financially?",
  "Low upfront cost, internal savings first, and a 90-day decision point before any big spend.", None),
 ("Does it scale?",
  "The software scales with the network. Each new city needs a coverage audit and local calibration, and different climates need their own calibration.", None),
 ("What skills does it need?",
  "Data engineering, signal processing and a meteorology partner, for example IMD or an academic institute.", None),
 ("Networks change. Links get replaced by fibre.",
  "Yes, coverage evolves, so we re-audit. Because we combine sources, quality degrades gracefully instead of failing.", None),
])

S("The video vs the deck", "Judges saw the video. Own the change; don’t hide it.", [
 ("Your video said 95%. Now you say 68%. Which is it?",
  "Both are true, but they measure different things. The 95% was decision agreement including dry days, when both systems say “no”. The 68% is the stricter question: how many real rain events were caught. After stress-testing we lead with the stricter one.", None),
 ("Your video said every tower is a rain gauge.",
  "We learned only microwave links work, not fibre, and nobody knows Jio’s usable coverage yet. That’s why coverage is now Gate 1.", None),
 ("Your video said ₹174 crore.",
  "That was an illustrative premium pool from a B2C assumption we can’t prove, and premiums aren’t Jio revenue. We removed it.", None),
 ("Your video said ₹300 lands in a JioPay wallet within hours.",
  "A licensed insurer would pay through its own rail. ₹300 is a prototype assumption, and nothing depends on JioPay.", None),
 ("Your video was riders first. Now it’s Reliance first?",
  "Riders still matter; Kavach is still on the roadmap. Proving value inside Reliance first lowers the risk before platforms are asked to pay.", None),
 ("Why should we trust a pitch that changed?",
  "Because it changed for evidence. We tested our own idea and kept what survived.", None),
])

S("Curveballs", "", [
 ("Why now?",
  "Quick commerce makes zone-level rain decisions worth more; extreme rain events are rising; operators keep adding microwave backhaul; and IMD keeps adding radars, which are inputs we combine.", None),
 ("If Reliance says no, what happens?",
  "Then the 90-day audit is the cheapest way to say no with evidence instead of opinion.", None),
 ("If you had to cut one thing, what?",
  "Kavach. The intelligence business stands without it.", None),
 ("What did you learn doing this?",
  "That a flattering number (0.95) can hide the number that matters (68%), and that testing your own idea is the fastest way to improve it.", None),
 ("Explain it to a 10-year-old.",
  "When it rains, the invisible radio beams between phone towers get weaker. We measure how much weaker to work out where it’s raining, and tell businesses which areas to act on.", None),
 ("How is this “Different by Design”?",
  "It uses infrastructure Jio already runs as a sensor, it’s designed around decisions instead of maps, and it’s built to be tested and stopped cheaply instead of launched on faith.", None),
])
