# Part D: backup plans. (assumption, how we find out, plan B, plan C)
BACKUP = [
 ("Jio has enough usable microwave links where it matters",
  "Gate 1 coverage audit (days 1–30): link counts, frequencies, path lengths, telemetry",
  "Run the layer on radar + gauges + satellite, plus network-health data for Jio’s own operations; focus first on areas where microwave is dense",
  "Add rain gauges on Jio sites where links are thin; if coverage is poor everywhere, the Jio-specific edge is small, so stop external scaling"),
 ("Jio’s telemetry is stored often enough and far enough back",
  "Gate 1: sampling interval, history kept, access route",
  "Use 15-minute minimum/maximum data (it worked country-wide in the Netherlands); start live polling for forward collection",
  "Use link alarm and outage logs as a coarse rain signal; back-test on whatever history exists"),
 ("Combining sources reaches ≥80% of trigger events, ±10% totals, <15% unconfirmed",
  "Gate 2 back-test on archived Mumbai monsoon data against held-out gauges",
  "Local calibration, more gauges, better fusion; use the system for decisions that need less precision (network ops, soft alerts)",
  "Kavach stays in shadow or is dropped; no external scaling"),
 ("Jio’s links add accuracy beyond radar + gauges",
  "Gate 2: “radar + gauges, no links” baseline vs every mix with links",
  "Keep links only where they add value (gaps between gauges, rural backhaul); sell the decision layer on the best mix",
  "If links add nothing anywhere, say so: the moat shrinks to integration and distribution, and the go/no-go is decided on that basis"),
 ("A Reliance operation sees measurable value",
  "Gate 3: matched zones with vs without JioMausam (site visits, fault time, delays, cancellations, incentive spend)",
  "Try another internal operation or a different decision (e.g. flood alerts for sites, staffing)",
  "Stop. A cheap, evidence-based no"),
 ("External businesses will pay",
  "After Gate 3: paid pilots with one platform and one logistics firm",
  "Bundle alerts into Jio’s enterprise connectivity offers as a value-add",
  "Keep it internal, or license data to insurers and agriculture"),
 ("A licensed insurer partners for Kavach",
  "Months 4–12: shadow results shared with insurers; regulator’s sandbox",
  "Platforms self-fund a weather allowance using our trigger data (no insurance needed)",
  "Drop Kavach; the intelligence business is untouched"),
 ("The price assumptions hold (₹300, 60%, 5-day cap)",
  "Actuarial review; shadow-mode payout data",
  "Change the benefit, cap or trigger (e.g. a 3-day cap brings Plus to ₹125)",
  "Platform group cover instead of individual sales"),
 ("Who pays: platforms, co-funding or individuals",
  "Pilot willingness-to-pay tests with platforms and riders",
  "Co-funded model (platform + rider)",
  "Data-only product for platforms’ own schemes"),
 ("Security and legal teams allow the data use",
  "Early review with Jio’s security and legal teams",
  "Process everything inside Jio; release only aggregated rain per zone",
  "Use the layer internally only (network ops)"),
 ("Accuracy holds in extreme rain (links can drop out)",
  "Gate 2 back-test on the heaviest archived events",
  "Treat drop-outs as “rain above a level”; lean on radar and gauges in those minutes",
  "Flag extreme events for manual review before any payout"),
 ("Heat can be covered by the same engine",
  "Months 4–12: April–June heat season with IMD stations and satellite",
  "Heat alerts first, insurance later",
  "Leave heat out; rain only"),
 ("Competitors (another telecom or a weather firm) move first",
  "Market watch during the pilot",
  "Compete on accuracy in our zones and on Reliance integration",
  "Partner or license; a competitor confirms the market"),
]
KILL = ["Gate 1: too few usable links and no telemetry access in the candidate cities → stop the Jio-links track; decide whether a radar-and-gauge decision layer is still worth it.",
        "Gate 2: no mix clears the accuracy gates → no external scaling; Kavach stays in shadow or is dropped.",
        "Gate 3: no measurable improvement in a Reliance operation → stop before spending on sales.",
        "Kavach: no insurer or no payer after shadow mode → drop Kavach; keep intelligence."]
LADDER = [("Full system", "Jio links + network health + radar + gauges (+ satellite, new gauges, paid data only if they earn their cost)"),
          ("Links thin", "Radar + gauges + satellite, network health for Jio operations, gauges on Jio sites"),
          ("Accuracy short", "Soft operational alerts and network operations only; no payouts"),
          ("No value shown", "Stop, with evidence, after about 90 days")]

NUMBERS = [
 ("944 vs 73 mm", "Fact", "IMD rainfall, Santacruz vs Colaba, 26 July 2005"),
 ("15 heavy days, 5 with less than half", "Our calculation", "IMD station reports (NOAA archive), 2020–2024 monsoons"),
 ("Science 2006 · PNAS 2013", "Fact", "Messer et al. (doi:10.1126/science.1120034) · Overeem et al. (doi:10.1073/pnas.1217961110)"),
 ("500 links, 11 days", "Fact", "pycomlink public dataset (KIT), github.com/pycomlink/pycomlink"),
 ("68% (1,120 of 1,639)", "Our calculation", "Our code on that dataset, German Weather Service radar as reference"),
 ("0.95 · 0.88 · 0.78 · 18% low · 18% unconfirmed", "Our calculation", "Same run; Q&A only"),
 ("80% · ±10% · <15%", "Our target", "Pilot gates"),
 ("10 mm in 3 h, ~4 km zone", "Our assumption", "Event rule; 5 and 15 mm also tested (64%, 54%)"),
 ("1.1 / 2.2 / 0.7 / 11.9 days a year", "Our calculation", "Counted from IMD station reports, 2000–2024"),
 ("204.5 / 115.6 / 64.5 mm a day", "Fact", "IMD rain categories"),
 ("47°C", "Our assumption", "Rare-heat trigger (45°C ≈ IMD heatwave level, too frequent)"),
 ("₹45 / ₹52 / ₹29 / ₹208", "Our calculation", "Paid days × ₹300 ÷ 0.6 ÷ 12; ₹29 is our minimum"),
 ("₹300 · 60% · 5-day cap", "Our assumption", "Prototype; actuary sets"),
 ("222% / 242% / 469%; Plus 60%", "Our calculation", "Stress test, every year 2000–2024"),
 ("₹12.5 crore pool; ₹1.9–3.1 crore fees", "Our calculation", "50,000 riders × ₹208 × 12; 15–25% fee (illustrative, Q&A only)"),
 ("90 days, three gates", "Plan", "Our pilot design"),
]
NEVER = [("“We tested Jio’s network.”", "“We ran the published method on public research data from Germany.”"),
         ("“Studies show 68%.”", "“In our own check, links alone caught 68%.”"),
         ("“Jio can already sense the weather.” / “Every tower is a rain gauge.”", "“Jio’s microwave links may carry a usable weather signal.”"),
         ("“80% is the industry standard.”", "“80% is our go/no-go bar, set above the 68% baseline.”"),
         ("“Reliance is our first customer.”", "“Reliance is our first proving ground.”"),
         ("“₹300 goes to the rider’s JioPay wallet.”", "“A licensed insurer would pay, through its own rail.”"),
         ("“We make ₹174 crore.”", "Don’t raise it. If asked: an illustrative premium pool, not Jio revenue."),
         ("“Only Reliance can do this.”", "“The edge is integration, not the sensor.”"),
         ("“Low cost” / “free” about any source", "“The pilot prices each source.”"),
         ("“We built a model.”", "“We ran the published method and calculated the result ourselves.”"),
         ("“False triggers.”", "“Triggers not confirmed by radar.”"),
         ("Naming a city for the live test", "“The coverage audit selects the city.”")]
CHEAT = ["India doesn’t have a weather-data problem; it has a weather-decision problem.",
         "Jio’s microwave links may carry a weather signal. Fibre doesn’t.",
         "The physics is well established. We tested it ourselves on public German data, not Jio’s.",
         "Links alone caught 68% of rain events (1,120 of 1,639). Our bar is 80%.",
         "So accuracy decides the mix: links, network health, radar, gauges, satellite. Cheapest mix that clears the bar.",
         "Reliance is the first proving ground. Hero test: rain or equipment fault, before sending a crew?",
         "Then sell the same intelligence. Jio sends the alert; the customer decides.",
         "The edge is integration, not the sensor.",
         "Insurance is one application: only after the gates, a licensed insurer carries the risk.",
         "Prices are illustrative: paid days × ₹300 ÷ 60% ÷ 12. ₹208 is not from the 3-hour rule.",
         "90 days, three gates: coverage, accuracy, value. The audit picks the city. If yes, scale; if not, stop.",
         "First prove the signal. Then sell the intelligence. Protection comes last."]
