# Part A (what changed) and Part B (deck slide by slide)
CHANGES = [
 ("“India’s biggest weather network already exists… lakhs of stations… every tower is a rain gauge.”",
  "“Jio’s microwave links <b>may</b> carry a weather signal.”",
  "Only microwave links react to rain; fibre does not. Nobody outside Jio knows how many usable links it has, so “lakhs” and “every tower” were claims we could not back. Coverage is now Gate 1."),
 ("“Our rain readings matched national radar at 0.95.”",
  "“Links tracked radar closely, but alone caught only 68% of rain events. Our bar is 80%.”",
  "0.95 is how well the <i>network average</i> follows radar hour by hour; local errors cancel out, so it flatters. What matters for alerts and payouts is how many real events are caught."),
 ("“Our payout rule made the same decision as radar 95% of the time.”",
  "“68% of rain events caught.” (94.6% kept for Q&A only)",
  "94.6% agreement is mostly dry days where both said “no”. It is true but misleading as a headline."),
 ("“We built it… on 500 real microwave links.”",
  "“500 real links from a public dataset in Germany, <b>not Jio’s</b>.”",
  "The old wording could make a judge think we had Jio data. We never did."),
 ("“A live, street-level weather map… minute by minute.”",
  "“Decision infrastructure, not a weather map”; “spatial weather grid”; “near-real-time”.",
  "Resolution depends on link density and refresh rate depends on telemetry; both are pilot questions. And nobody pays for a map; they pay for better decisions."),
 ("“Delivery apps buy Kavach for riders… ₹300 lands in the rider’s JioPay wallet within hours.”",
  "“Insurance is one application, not the anchor. A licensed insurer would underwrite and pay.” ₹300 = prototype assumption.",
  "Who pays is unproven, Jio cannot carry insurance risk, links alone are not accurate enough to pay claims on, and the payment rail is the insurer’s choice."),
 ("“50,000 riders ≈ ₹12 crore of premiums; 1% of Jio users = ₹174 crore.”",
  "Removed from the deck. Q&A only, always called a <i>premium pool</i>, never Jio revenue.",
  "Premiums belong to the insurer, B2C uptake is a guess, and big numbers invite attack without adding proof."),
 ("“Later, workers add Kavach Basic at recharge.”",
  "Reliance first, then businesses. “Basic at recharge” stays only as an optional Year-2 roadmap item.",
  "Selling insurance directly to individuals is hard (trust, adverse selection, licensing). B2B decisions are a clearer first market."),
 ("“Why only Reliance?… No other telecom has…”",
  "“The edge is integration, not the sensor.”",
  "“Only” is absolute and easy to attack (Airtel has towers; weather firms have radar). Integration across Sense → Understand → Reach → Protect is defensible."),
 ("“It pays three ways” (premiums, recharge add-on, data sales).",
  "“How Jio creates value”: intelligence fees (external), savings inside Reliance (internal), distribution fees (optional).",
  "Savings are not revenue, and the business must stand even if insurance never launches."),
 ("Heat in Nagpur and Ahmedabad as Phase 2 of the same tower system.",
  "Rain from Jio’s links; heat from IMD stations and satellite through the same engine.",
  "Microwave attenuation is rain physics. Links do not sense temperature."),
 ("“About forty radars can’t see that difference.”",
  "Radar is an input we combine, not a rival.",
  "Attacking IMD invites “then just use radar”. Our position: links + radar + gauges, and accuracy decides the mix."),
 ("Phase 1: 90-day Mumbai audit with shadow payouts.",
  "Three gates (coverage, accuracy, value), overlapping phases; the coverage audit selects the live-test city; stop or scale.",
  "Clear go/no-go points, and we cannot pre-select a city before knowing its coverage."),
]
DRAFT_FIXES = [
 ("“Reliance is the first customer”", "“first proving ground”", "Reliance has not agreed to buy anything."),
 ("Six internal uses (incl. JioAds, Reliance Foundation, JFS)", "Three: network ops (hero), JioMart, MyJio", "Fewer, provable uses beat “weather for everything”."),
 ("“Layer the sources, cheapest first”", "“Let accuracy determine the mix”", "An insurance-grade system should not start from cheapest."),
 ("“A sensor on every link, far denser than gauges, early warning, strongest in rural areas, independent trigger”", "“Dense sensing wherever usable links exist”, “potentially denser”, “near-real-time monitoring”, “auditable multi-source trigger”", "Each original claim was unproven or wrong (detection is not prediction; Jio’s own system is not “independent”)."),
 ("“Others hold one or two of these layers”", "Deleted", "Unprovable competitor claim."),
 ("“Low cost”, “Free” cost labels", "Source labels: Jio-owned, IMD (govt), IMD · BMC, External, New install, Commercial", "We cannot prove prices; we can state who provides each source."),
 ("“18% false triggers”", "“18% of our triggers not confirmed by radar”", "Radar is not perfect truth."),
 ("Heat cards at 45°C (9.7 and 5.4 days)", "47°C (2.2 and 0.7 days), matching the price table", "The cards and the product used different triggers."),
 ("“for platforms to sponsor”", "“designed for potential platform sponsorship, subject to pilot validation”", "Slide 8 says who pays is unproven."),
 ("“Indian weather sets the price”", "“weather risk sets the starting price”", "Loss ratio, costs and reinsurance also set price."),
]
KEPT = ["The 944 mm vs 73 mm Mumbai story (26 July 2005)", "Mumbai first, rain first, heat as Phase 2",
        "About 12 heavy-rain days a year in Mumbai (IMD, 2000–2024)", "Kavach Basic ₹45 / ₹52 / ₹29 and Plus ₹208 a month",
        "90 days with shadow payouts first; IRDAI sandbox and heat in months 4–12", "The roadmap labels (Basic at recharge in Year 2, national scale in Year 3)"]

SLIDES = [
 dict(n=1, title="India has a weather-decision problem",
  purpose="Make the problem concrete in ten seconds: the data exists, but it is too coarse to act on zone by zone.",
  screen=["Bar chart: Santacruz 944 mm vs Colaba 73 mm, 26 July 2005, stations ~20 km apart (IMD)",
          "“What a city-level alert says: Heavy rain in Mumbai” → “What it needs to decide: Which zones do I act on, right now?”",
          "Businesses decide blind · Workers carry the loss"],
  nums=[("944 vs 73 mm", "Fact", "IMD rainfall records")],
  watch="Present the alert as imagined (“Imagine you’re running deliveries…”), not as something a named business receives. If they say “one day proves nothing”, use the 2020–24 station comparison (Part C, “The problem and the idea”)."),
 dict(n=2, title="Jio’s microwave links may carry a weather signal",
  purpose="The insight, and a precise definition of JioMausam.",
  screen=["Two towers and a microwave link; rain weakens the signal; measure the excess loss → path-averaged rainfall, near-real-time",
          "“This technique uses microwave links, not fibre.”",
          "JioMausam is decision infrastructure, not a weather map: link signals + IMD radar + gauges → spatial weather grid → decision-ready alerts and triggers",
          "It is / It isn’t (not a new sensor network, not a consumer weather app, not an insurer, no heat sensing from towers)",
          "Takeaway: “Jio may already own the infrastructure for a new weather-sensing layer.”"],
  nums=[],
  watch="Keep “may”. Never say “every tower is a rain gauge” or that Jio can already sense the weather."),
 dict(n=3, title="Links alone are promising, but fall short of our bar",
  purpose="Credibility: show what is proven, what we checked ourselves, what is not proven, and the honest limit.",
  screen=["Proven · published: the physics; Science 2006; PNAS 2013 (rain mapped across a whole country)",
          "Our check · public data: we ran the open-source method on 500 real links with radar as reference",
          "Not yet proven · the pilot: Jio’s coverage, Indian accuracy, business value, who pays, insurance-grade triggers",
          "Banner: OUR CHECK · 500 REAL LINKS · PUBLIC RESEARCH DATA, GERMANY · NOT JIO DATA",
          "68% of rain events caught by links alone, against our 80% bar; event = 10 mm+ in 3 hours in a ~4 km zone; 8 unseen test days",
          "Chart: network average, hour by hour, links vs radar"],
  nums=[("68%", "Our calculation", "pycomlink public dataset (KIT), German radar"), ("80%", "Our target", "Pilot go/no-go bar"),
        ("10 mm in 3 h", "Our assumption", "Event rule; 5 and 15 mm also tested"), ("Science 2006, PNAS 2013", "Fact", "Published papers")],
  watch="Never say “studies show 68%” (it is ours) or “we tested Jio’s network”. Mention 0.95 only if asked."),
 dict(n=4, title="Let accuracy determine the mix",
  purpose="Answer the limit: combine sources, test every mix, keep the cheapest that clears the bar.",
  screen=["Sources and providers: Jio microwave links (Jio-owned) · network health: faults, outages, maintenance (Jio-owned) · Doppler radar (IMD, govt) · rain gauges (IMD · BMC) · satellite (External) · new gauges on Jio sites (New install) · commercial data (Commercial)",
          "Mix bars scored against held-out rain gauges: Links only = our check 68%; other mixes “measured in the pilot”; “Radar + gauges, no links” shows what Jio adds",
          "Rule: the lowest-cost mix that clears every accuracy gate (≥80% of predefined trigger events, totals within ±10%, under 15% unconfirmed)"],
  nums=[("68%", "Our calculation", "Same as slide 3"), ("80%, ±10%, <15%", "Our targets", "Pilot gates")],
  watch="The pilot does the scoring; we have not done it yet. No prices are claimed; labels show who provides each source."),
 dict(n=5, title="Reliance is the first proving ground",
  purpose="Remove the biggest commercial risk: prove value inside Reliance before selling outside.",
  screen=["Hero: Jio network operations. Can we tell rain-related signal loss from equipment faults before sending a crew? Potentially fewer wasted visits and earlier flood alerts. Jio owns the network data and controls the operational decision.",
          "“Before Jio sells weather intelligence to anyone, it uses it to understand its own network.”",
          "JioMart and Reliance Retail: rain-aware dispatch, delivery promises, zone pauses (tests commercial value)",
          "MyJio: street-level rain alerts (tests reach at scale)"],
  nums=[],
  watch="Everything here is a hypothesis to test, not a result. Say “proving ground”, never “first customer”."),
 dict(n=6, title="Then sell the same intelligence to the market",
  purpose="External market, and what the product actually is.",
  screen=["Tiers: 1 delivery, quick commerce, ride-hailing (Alerts) · 2 logistics, cities and transport, insurers (Alerts + data) · 3 agriculture, power, construction, retail (Data + alerts)",
          "Example chain: Rain hits Zone A → JioMausam sends zone alert + rain estimate → the customer decides (dispatch, ETAs, incentives) → lower disruption",
          "Why buy from us: dense sensing wherever usable links exist · potentially denser than gauges · near-real-time monitoring · potentially valuable wherever microwave backhaul is present · auditable trigger from multiple sources"],
  nums=[],
  watch="Company names are examples of buyers, not customers we have spoken to. Jio sells intelligence; the customer owns the decision."),
 dict(n=7, title="The edge is integration, not the sensor",
  purpose="Why Jio, and how value is created without insurance risk.",
  screen=["Sense (Jio network) → Understand (JioMausam) → Reach (Reliance ecosystem) → Protect (JFS + licensed insurers, optional)",
          "“Reliance can connect all four layers, so Jio earns from the intelligence without carrying insurance risk.”",
          "How Jio creates value: 01 external revenue, intelligence fees · 02 external, optional, distribution fees · 03 internal value, savings inside Reliance"],
  nums=[],
  watch="No claims about competitors. JFS is a separately listed group company; any deal would be at arm’s length."),
 dict(n=8, title="Insurance is one application, not the anchor",
  purpose="Show the pivot from the video, and that insurance is gated.",
  screen=["Flow: qualifying weather event in a zone → JioMausam supplies the trigger data → a licensed insurer would underwrite and pay → fixed benefit to the worker, e.g. ₹300",
          "Eligible = already active in the zone before the event began (predefined rules); ₹300 is a prototype assumption",
          "Why optional: only after accuracy and actuarial gates (shadow payouts until then) · who pays is unproven · the insurer carries the risk, never Jio · if it fails, nothing breaks"],
  nums=[("₹300", "Our assumption", "Prototype benefit")],
  watch="No insurer partner yet: always “would”. Kicker reads “Where we started”: own the pivot."),
 dict(n=9, title="If we offer Kavach, weather risk sets the starting price",
  purpose="Keep continuity with the video’s pricing, and show prices come from data.",
  screen=["Table: Mumbai Basic ≥204.5 mm/day (1.1 days → ₹45) · Nagpur ≥47°C (2.2 raw, ~1.2 paid → ₹52) · Ahmedabad ≥47°C (0.7, ~0.6 → ₹29 floor) · Mumbai Plus ≥64.5 mm/day (11.9 raw, 5 paid → ₹208)",
          "Price = expected paid days × ₹300 ÷ 60% ÷ 12",
          "City cards: Mumbai 11.9 heavy-rain days a year (Phase 1) · Nagpur 2.2 and Ahmedabad 0.7 days at 47°C+ (Phase 2)",
          "Footer: ₹300 and 60% are prototype assumptions; 5-day annual cap; final pricing subject to actuarial validation"],
  nums=[("Trigger levels 204.5 / 64.5 mm", "Fact", "IMD rain categories"), ("47°C", "Our assumption", "Rare heat level"),
        ("Days a year, paid days", "Our calculation", "Counted from 25 years of IMD station reports"), ("Prices", "Our calculation", "Formula above")],
  watch="₹208 is not priced from the 10 mm-in-3-hours rule. All prices are illustrative."),
 dict(n=10, title="Don’t believe us. Test it in 90 days",
  purpose="A concrete, low-risk ask with stop/scale points.",
  screen=["Days 1–30 Coverage (Gate 1: enough usable coverage?) · Days 15–60 Accuracy (Gate 2: fused system clears every gate?) · Days 61–90 Value (Gate 3: improves a real Reliance operation? matched zones with and without JioMausam)",
          "Roadmap: 0–3 m three gates / shadow payouts · 4–12 m Reliance live + first clients / sandbox + heat · Year 2 cities + enterprises / Basic at recharge · Year 3 national weather API / national scale",
          "“Only after all three gates pass do we scale externally.”",
          "Close: “We aren’t asking Jio to build another weather network…”; “First prove the signal. Then sell the intelligence. Protection comes last.”"],
  nums=[("90 days, gates", "Plan / targets", "Our pilot design")],
  watch="“We don’t pre-select the city; the coverage audit does.”"),
]
